# $FreeBSD: src/sys/modules/udf_iconv/Makefile,v 1.1 2003/11/07 09:38:05 scottl Exp $

.PATH:	${.CURDIR}/../udf2
KMOD=	udf2_iconv
SRCS=	udf_iconv.c

CFLAGS+= -I${.CURDIR}/../udf2

.include <bsd.kmod.mk>
